const { app, BrowserWindow, nativeTheme } = require('electron');
const path = require('node:path');
const fs = require('node:fs');
app.setPath('userData', path.join(require('node:os').tmpdir(), 'chr-organizer-ui-test'));
app.whenReady().then(async () => {
  const window = new BrowserWindow({ show: false, width: 1280, height: 850, webPreferences: { sandbox: true, contextIsolation: true, nodeIntegration: false } });
  const errors = [];
  window.webContents.on('console-message', event => { if (event.level === 'error') { errors.push(event.message); console.error(event.message); } });
  await window.loadFile(path.join(__dirname, '../src/index.html'));
  await window.webContents.executeJavaScript(`(async () => {
    const assert = (condition, message) => { if (!condition) throw new Error(message); };
    const tick = () => new Promise(resolve => setTimeout(resolve, 50));
    const divider = document.querySelector('#sidebar-resizer');
    divider.dispatchEvent(new MouseEvent('dblclick', { bubbles: true }));
    divider.focus(); divider.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
    assert(document.querySelector('.sidebar').getBoundingClientRect().width === 245, 'Sidebar keyboard resize failed');
    assert(localStorage.getItem('sidebarWidth') === '245', 'Sidebar width not saved');
    divider.dispatchEvent(new MouseEvent('dblclick', { bubbles: true }));
    document.querySelector('#app-menu-toggle').click();
    assert(!document.querySelector('#app-menu').hidden && document.activeElement.id === 'setup', 'Workspace menu did not open with keyboard focus');
    document.activeElement.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
    assert(document.querySelector('#app-menu').hidden && document.activeElement.id === 'app-menu-toggle', 'Menu Escape did not restore focus');
    document.querySelector('#app-menu-toggle').click();
    document.querySelector('#demo').click();
    assert(document.querySelector('#app-menu').hidden, 'Choosing menu action did not dismiss menu');
    assert(document.querySelector('.tab-row').getBoundingClientRect().height === 54, 'Compact row height incorrect');
    assert(document.querySelector('header').contains(document.querySelector('#search')), 'Search is not in header');
    assert(document.querySelector('#result-count').textContent === '14 of 14 tabs', 'Demo rows missing');
    assert(document.querySelectorAll('.window-icon').length === 3, 'Chrome window icons missing');
    assert(document.querySelector('.nav-group[data-group-color="purple"]'), 'Sidebar group color missing');
    assert(document.querySelector('.group-chip[data-group-color="blue"]'), 'Tab group color missing');
    const selectionRows = [...document.querySelectorAll('.tab-row')];
    selectionRows[0].querySelector('input').click();
    selectionRows[1].querySelector('input').click();
    selectionRows[2].click();
    assert(document.querySelector('#selection-count').textContent === '3 selected', 'Clicking beside checkbox cleared other selections');
    selectionRows[2].click();
    assert(document.querySelector('#selection-count').textContent === '2 selected', 'Row toggle changed other selected tabs');
    document.querySelector('#clear-selection').click();
    const duplicateNav = [...document.querySelectorAll('.nav-button')].find(b => b.textContent.includes('Duplicates'));
    duplicateNav.click();
    assert(document.querySelectorAll('.duplicate-badge').length === 4, 'Duplicate copy indicators missing');
    document.querySelector('.cluster-select input').click();
    assert(document.querySelector('#selection-count').textContent === '2 selected', 'Cluster checkbox did not select every copy');
    document.querySelector('.tab-row > input').click();
    assert(document.querySelector('.cluster-select input').indeterminate, 'Partial cluster selection not indicated');
    document.querySelector('.cluster-select input').click();
    assert(document.querySelector('#selection-count').textContent === '2 selected', 'Cluster checkbox did not complete partial selection');
    document.querySelector('.cluster-select input').click();
    assert(document.querySelector('#selection-bar').hidden, 'Cluster deselect failed');

    const duplicateUrls = [...document.querySelectorAll('.tab-url')].map(el => el.textContent);
    assert(duplicateUrls[0] === duplicateUrls[1] && duplicateUrls[2] === duplicateUrls[3], 'Duplicate copies are not adjacent');
    document.querySelector('.nav-button').click();
    const search = document.querySelector('#search'); search.value = 'mydealz'; search.dispatchEvent(new Event('input'));
    assert(document.querySelectorAll('.tab-row').length === 4, 'Search did not filter');
    document.querySelector('#select-all').click();
    assert(document.querySelector('#selection-count').textContent === '4 selected', 'Select visible failed');
    document.querySelector('#group-selection').click();
    assert(document.querySelector('#organize-dialog').open, 'Group dialog failed');
    document.querySelector('#group-name').value = 'Deals';
    document.querySelector('#organize-form').requestSubmit(); await tick();
    assert(document.querySelector('#status').textContent.includes('Grouped 4'), 'Group action failed');
    assert([...document.querySelectorAll('.group-chip')].every(el => el.textContent === 'Deals'), 'Group location not updated');
    const closable = [...document.querySelectorAll('.row-actions button')].find(el => el.textContent === '×' && !el.disabled);
    closable.click(); await tick();
    assert(document.querySelectorAll('.tab-row').length === 3, 'Row close failed');
    document.querySelector('#close-selection').click();
    assert(document.querySelector('#close-dialog').open, 'Bulk-close dialog failed');
    document.querySelector('#confirm-close').click(); await tick();
    assert(document.querySelectorAll('.tab-row').length === 1, 'Protected active tab was not preserved');
    document.querySelector('#demo').click(); document.querySelector('#demo').click();
    assert(document.querySelector('#result-count').textContent === '14 of 14 tabs', 'Demo reset failed');
    const sony = [...document.querySelectorAll('.tab-row')].find(row => row.querySelector('.tab-title').textContent.startsWith('Sony'));
    const transfer = new DataTransfer();
    sony.dispatchEvent(new DragEvent('dragstart', { bubbles: true, dataTransfer: transfer }));
    const target = [...document.querySelectorAll('.nav-button')].find(button => button.textContent.includes('Window 3'));
    target.dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer: transfer }));
    assert(document.querySelector('#drop-dialog').open, 'Drop preview missing');
    document.querySelector('#confirm-drop').click(); await tick();
    const movedSony = [...document.querySelectorAll('.tab-row')].find(row => row.querySelector('.tab-title').textContent.startsWith('Sony'));
    assert(movedSony.querySelector('.location').textContent.includes('Window 3'), 'Drag/drop did not move tab');
    movedSony.dispatchEvent(new MouseEvent('contextmenu', { bubbles: true, clientX: 400, clientY: 350 }));
    assert(!document.querySelector('#context-menu').hidden, 'Context menu missing');
    document.querySelector('#context-focus').click(); await tick();
    assert(document.querySelector('#status').textContent.includes('Focused 1'), 'Context menu focus failed');

    document.querySelector('#cleanup').click();
    assert(document.querySelector('#cleanup-dialog').open, 'Cleanup dialog missing');
    const suggestions = document.querySelectorAll('#cleanup-list input:checked').length;
    assert(suggestions === 4, 'Expected two duplicates and two empty tabs');
    document.querySelector('#apply-cleanup').click(); await tick();
    assert(document.querySelector('#result-count').textContent === '10 of 10 tabs', 'Suggested cleanup did not close expected tabs');
    document.querySelector('#recovery').click(); await tick();
    const restore = [...document.querySelectorAll('#recovery-list button')].find(button => button.textContent === 'Reopen closed tabs');
    assert(restore, 'Recovery entry missing'); restore.click(); await tick();
    assert(document.querySelector('#result-count').textContent === '14 of 14 tabs', 'Recovery did not reopen tabs');
    document.querySelector('[data-dismiss="recovery-dialog"]').click();
    document.querySelector('#settings').click();
    document.querySelector('#keep-domains').value = 'mydealz.de';
    document.querySelector('#settings-form').requestSubmit(); await tick();
    document.querySelector('#cleanup').click();
    assert(document.querySelectorAll('#cleanup-list input:checked').length === 3, 'Keep-domain preferences were ignored');
    document.querySelector('[data-dismiss="cleanup-dialog"]').click();

    const windowButton = [...document.querySelectorAll('.window-icon')][0].parentElement;
    windowButton.dispatchEvent(new MouseEvent('contextmenu', { bubbles: true, clientX: 100, clientY: 150 }));
    assert(!document.querySelector('#window-menu').hidden, 'Window menu missing');
    document.querySelector('#window-focus').click(); await tick();
    assert(document.querySelector('#status').textContent.includes('Brought Window 1'), 'Window focus failed');
    windowButton.dispatchEvent(new MouseEvent('contextmenu', { bubbles: true, clientX: 100, clientY: 150 }));
    document.querySelector('#window-close').click();
    assert(document.querySelector('#close-window-dialog').open, 'Window close did not ask for confirmation');
    document.querySelector('[data-dismiss="close-window-dialog"]').click();
    assert(document.querySelectorAll('.window-icon').length === 3, 'Cancelling closed a window');
    windowButton.dispatchEvent(new MouseEvent('contextmenu', { bubbles: true, clientX: 100, clientY: 150 }));
    document.querySelector('#window-close').click(); document.querySelector('#confirm-close-window').click(); await tick();
    assert(document.querySelectorAll('.window-icon').length === 2, 'Confirmed window close failed');
    document.querySelector('#recovery').click(); await tick();
    [...document.querySelectorAll('#recovery-list button')].find(b => b.textContent === 'Reopen closed tabs').click(); await tick();
    assert(document.querySelector('#result-count').textContent === '14 of 14 tabs', 'Window recovery did not restore tabs');
    document.querySelector('[data-dismiss="recovery-dialog"]').click();
    document.querySelector('#demo').click(); document.querySelector('#demo').click();

    document.querySelector('#search').value = 'chrome://newtab/'; document.querySelector('#search').dispatchEvent(new Event('input'));
    document.querySelector('#select-all').click(); document.querySelector('#close-selection').click();
    assert(document.querySelector('#close-dialog').open, 'Initial tab close must ask');
    document.querySelector('#ask-tab-close').checked = false;
    document.querySelector('#confirm-close').click(); await tick();
    document.querySelector('#demo').click(); document.querySelector('#demo').click();
    document.querySelector('#search').value = 'chrome://newtab/'; document.querySelector('#search').dispatchEvent(new Event('input'));
    document.querySelector('#select-all').click(); document.querySelector('#close-selection').click(); await tick();
    assert(!document.querySelector('#close-dialog').open && document.querySelector('#result-count').textContent === '0 of 12 tabs', 'Remembered tab-close preference did not skip prompt');
    document.querySelector('#settings').click();
    assert(!document.querySelector('#confirm-tab-close-setting').checked && document.querySelector('#confirm-window-close-setting').checked, 'Tab preference affected window confirmation');
    document.querySelector('#confirm-tab-close-setting').checked = true; document.querySelector('#settings-form').requestSubmit(); await tick();
    document.querySelector('#demo').click(); document.querySelector('#demo').click();
    [...document.querySelectorAll('.nav-button')].find(b => b.textContent.includes('Duplicates')).click();

  })()`);
  const dividerBounds = await window.webContents.executeJavaScript(`(() => { const r = document.querySelector('#sidebar-resizer').getBoundingClientRect(); return { x: Math.round(r.x + r.width / 2), y: 200 }; })()`);
  window.show(); window.focus();
  await new Promise(resolve => setTimeout(resolve, 150));
  window.webContents.sendInputEvent({ type: 'mouseMove', ...dividerBounds });
  window.webContents.sendInputEvent({ type: 'mouseDown', ...dividerBounds, button: 'left', clickCount: 1 });
  await new Promise(resolve => setTimeout(resolve, 50));
  window.webContents.sendInputEvent({ type: 'mouseMove', x: dividerBounds.x + 60, y: dividerBounds.y, movementX: 60, movementY: 0 });
  await new Promise(resolve => setTimeout(resolve, 50));
  window.webContents.sendInputEvent({ type: 'mouseUp', x: dividerBounds.x + 60, y: dividerBounds.y, button: 'left', clickCount: 1 });
  await new Promise(resolve => setTimeout(resolve, 50));
  await window.webContents.executeJavaScript(`if (document.querySelector('.sidebar').getBoundingClientRect().width !== 295) throw new Error('Dragging sidebar divider failed: ' + document.querySelector('.sidebar').getBoundingClientRect().width);`);
  window.setSize(900, 600);
  await new Promise(resolve => setTimeout(resolve, 100));
  await window.webContents.executeJavaScript(`if (document.querySelector('#search').getBoundingClientRect().right > innerWidth || document.querySelector('main').scrollWidth > document.querySelector('main').clientWidth) throw new Error('Compact layout overflows minimum window size'); document.querySelector('#sidebar-resizer').dispatchEvent(new MouseEvent('dblclick'));`);
  window.setSize(1280, 850);
  await new Promise(resolve => setTimeout(resolve, 150));
  await window.webContents.executeJavaScript(`document.querySelector('#theme').value = 'dark'; document.querySelector('#theme').dispatchEvent(new Event('change')); if (document.documentElement.dataset.theme !== 'dark') throw new Error('Dark mode switch failed');`);
  const image = await window.webContents.capturePage();
  fs.writeFileSync(path.join(require('node:os').tmpdir(), 'chr-organizer-preview.png'), image.toPNG());
  await window.webContents.reload();
  await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
  await window.webContents.executeJavaScript(`if (document.documentElement.dataset.theme !== 'dark' || document.querySelector('#theme').value !== 'dark') throw new Error('Theme did not survive reload'); document.querySelector('#theme').value = 'system'; document.querySelector('#theme').dispatchEvent(new Event('change'));`);
  nativeTheme.themeSource = 'dark';
  await new Promise(resolve => setTimeout(resolve, 100));
  await window.webContents.executeJavaScript(`if (document.documentElement.dataset.theme !== 'dark') throw new Error('System dark mode not applied');`);
  nativeTheme.themeSource = 'light';
  await new Promise(resolve => setTimeout(resolve, 100));
  await window.webContents.executeJavaScript(`if (document.documentElement.dataset.theme !== 'light') throw new Error('System light mode not applied');`);
  if (errors.length) throw new Error(errors.join('\n'));
  console.log('Desktop UI smoke passed: demo, search, selection, grouping, individual/bulk close, cleanup preview, recovery, and preferences. Screenshot: ' + path.join(require('node:os').tmpdir(), 'chr-organizer-preview.png'));
  app.quit();
}).catch(error => { console.error(error); app.exit(1); });
